### ISSUE TITLE
You should really start tagging your releases base on the version of your package.json

### ISSUE THREAD

**Issue by robertkraig** [dfcreative/st8#3]
It would be a really good idea for your project if you had tags for your releases so people could quickly run diffs between say..

```bash
git diff origin/v2.0.0...origin/v.3.0.0
```

because right now, I only see a straight up linear merge path. Yes publishing does have versioning, but your codebase really should also have tags that live along with the package.json bumps. 

Yes there are versions here: https://www.npmjs.com/package/st8 but not with the codebase and having pointers between version a & version b really will help people in the future.

**Comment by dy** [comment]
Sure, pushed tags.
